# Generated by Django 3.0.4 on 2020-04-25 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20200425_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
