# Generated by Django 3.0.4 on 2020-04-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_thread_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_pic',
            field=models.CharField(default='new.png', max_length=30),
        ),
    ]
