# Generated by Django 3.0.4 on 2020-04-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_userdetails_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='icon',
        ),
    ]
