# Generated by Django 3.0.4 on 2020-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_remove_postcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
