# Generated by Django 3.0.4 on 2020-04-26 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_userdetails_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
