# Generated by Django 3.0.4 on 2020-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_comment_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='edited_on',
            field=models.DateTimeField(null=True),
        ),
    ]
