# Generated by Django 3.0.4 on 2020-04-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_thread_edited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
