# Generated by Django 3.0.5 on 2020-04-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_userdetails_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='bio',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
